project_id = "cfrhwhpzpdhavksnsorz"

[functions.chat]
verify_jwt = false

[functions.uazapi-disparo-massa]
verify_jwt = false

[functions.process-message-queue]
verify_jwt = false

[functions.whatsapp-agent]
verify_jwt = false

[functions.daily-reminder]
verify_jwt = false

[functions.geocode]
verify_jwt = false

[functions.maps-key]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.processar-pdf-conhecimento]
verify_jwt = false

[functions.kiwify-webhook]
verify_jwt = false
